apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  PORT: "3000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.opentelemetry-collector.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "backend"
  RUST_LOG: "info,backend=trace"
