x-database-env: &database-env
  POSTGRES_USER: tester
  POSTGRES_PASSWORD: tester
  POSTGRES_DB: tester

services:
  db:
    image: "postgres:17-alpine"
    ports:
      - 5432:5432
    environment:
      <<: *database-env
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  # this service exists only to build the image
  rust-workspace:
    build:
      context: ./
      dockerfile: Dockerfile.rust-workspace
    image: rust-workspace
    profiles: ["build-only"]

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *database-env
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      RUST_LOG: "backend=trace"
    ports:
      - "3000:3000"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
  