export enum LoginError {
    INVALID_FORM_OBJECT = "INVALID_FORM_OBJECT",
    ILLFORMED_CREDENTIALS = "ILLFORMED_CREDENTIALS",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    TOO_SHORT_PASSWORD = "TOO_SHORT_PASSWORD",
    TOO_LONG_PASSWORD = "TOO_LONG_PASSWORD",
    TOO_SHORT_USERNAME = "TOO_SHORT_USERNAME",
    TOO_LONG_USERNAME = "TOO_LONG_USERNAME",
    CHESS_DOT_COM_ACCOUNT_NOT_FOUND = "CHESS_DOT_COM_ACCOUNT_NOT_FOUND",
    LICHESS_ACCOUNT_NOT_FOUND = "LICHESS_ACCOUNT_NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
