export enum LoginError {
    ILLFORMED_CREDENTIALS = "ILLFORMED_CREDENTIALS",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    TOO_SHORT_PASSWORD = "TOO_SHORT_PASSWORD",
    TOO_LONG_PASSWORD = "TOO_LONG_PASSWORD",
    TOO_SHORT_USERNAME = "TOO_SHORT_USERNAME",
    TOO_LONG_USERNAME = "TOO_LONG_USERNAME",
    CHESS_DOT_COM_ACCOUNT_NOT_FOUND = "CHESS_DOT_COM_ACCOUNT_NOT_FOUND",
    LICHESS_ACCOUNT_NOT_FOUND = "LICHESS_ACCOUNT_NOT_FOUND",
}
