[workspace]
members = ["backend"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4" }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-rustls-ring-webpki",
    "postgres",
] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
