[workspace]
members = ["backend"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4", features = ["macros"] }
derive_more = { version = "2.0.1", features = ["display"] }
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-rustls-ring-webpki",
    "postgres",
] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipauto = "0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
