{
 "title": "Backend Telemetry",
 "tags": [
  "main-line",
  "backend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"backend\"}"
    }
   ]
  },
  {
   "title": "Backend Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"backend\"} |= `ERROR`"
    }
   ]
  }
 ]
}
{
 "title": "Test Telemetry",
 "tags": [
  "main-line",
  "test"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Test Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"main-line-general-test\"}"
    }
   ]
  },
  {
   "title": "Test Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"main-line-general-test\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Test Metric Samples",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count({job=\"main-line-general-test\"})",
     "legendFormat": "Unique metrics"
    }
   ]
  }
 ]
}